/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A candidate item. 
    /// </summary>
    [DataContract(Name = "Candidate")]
    public partial class Candidate : IEquatable<Candidate>, IValidatableObject
    {
        /// <summary>
        /// Defines CandidateType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CandidateTypeEnum
        {
            /// <summary>
            /// Enum User for value: user
            /// </summary>
            [EnumMember(Value = "user")]
            User = 1,

            /// <summary>
            /// Enum Group for value: group
            /// </summary>
            [EnumMember(Value = "group")]
            Group = 2

        }


        /// <summary>
        /// Gets or Sets CandidateType
        /// </summary>
        [DataMember(Name = "candidateType", EmitDefaultValue = false)]
        public CandidateTypeEnum? CandidateType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Candidate" /> class.
        /// </summary>
        /// <param name="candidateType">candidateType.</param>
        /// <param name="candidateId">candidateId.</param>
        public Candidate(CandidateTypeEnum? candidateType = default(CandidateTypeEnum?), string candidateId = default(string))
        {
            this.CandidateType = candidateType;
            this.CandidateId = candidateId;
        }

        /// <summary>
        /// Gets or Sets CandidateId
        /// </summary>
        [DataMember(Name = "candidateId", EmitDefaultValue = false)]
        public string CandidateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Candidate {\n");
            sb.Append("  CandidateType: ").Append(CandidateType).Append("\n");
            sb.Append("  CandidateId: ").Append(CandidateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Candidate);
        }

        /// <summary>
        /// Returns true if Candidate instances are equal
        /// </summary>
        /// <param name="input">Instance of Candidate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Candidate input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CandidateType == input.CandidateType ||
                    this.CandidateType.Equals(input.CandidateType)
                ) && 
                (
                    this.CandidateId == input.CandidateId ||
                    (this.CandidateId != null &&
                    this.CandidateId.Equals(input.CandidateId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CandidateType.GetHashCode();
                if (this.CandidateId != null)
                {
                    hashCode = (hashCode * 59) + this.CandidateId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
