/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// Pagination
    /// </summary>
    [DataContract(Name = "Pagination")]
    public partial class Pagination : IEquatable<Pagination>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Pagination" /> class.
        /// </summary>
        /// <param name="count">The number of objects in the entries array. .</param>
        /// <param name="hasMoreItems">A boolean value which is **true** if there are more entities in the collection beyond those in this response. A true value means a request with a larger value for the **skipCount** or the **maxItems** parameter will return more entities. .</param>
        /// <param name="totalItems">An integer describing the total number of entities in the collection. The API might not be able to determine this value, in which case this property will not be present. .</param>
        /// <param name="skipCount">An integer describing how many entities exist in the collection before those included in this list. .</param>
        /// <param name="maxItems">The value of the **maxItems** parameter used to generate this list, or if there was no **maxItems** parameter the default value, 10 .</param>
        public Pagination(int count = default(int), bool hasMoreItems = default(bool), long totalItems = default(long), long skipCount = default(long), long maxItems = default(long))
        {
            this.Count = count;
            this.HasMoreItems = hasMoreItems;
            this.TotalItems = totalItems;
            this.SkipCount = skipCount;
            this.MaxItems = maxItems;
        }

        /// <summary>
        /// The number of objects in the entries array. 
        /// </summary>
        /// <value>The number of objects in the entries array. </value>
        [DataMember(Name = "count", EmitDefaultValue = false)]
        public int Count { get; set; }

        /// <summary>
        /// A boolean value which is **true** if there are more entities in the collection beyond those in this response. A true value means a request with a larger value for the **skipCount** or the **maxItems** parameter will return more entities. 
        /// </summary>
        /// <value>A boolean value which is **true** if there are more entities in the collection beyond those in this response. A true value means a request with a larger value for the **skipCount** or the **maxItems** parameter will return more entities. </value>
        [DataMember(Name = "hasMoreItems", EmitDefaultValue = true)]
        public bool HasMoreItems { get; set; }

        /// <summary>
        /// An integer describing the total number of entities in the collection. The API might not be able to determine this value, in which case this property will not be present. 
        /// </summary>
        /// <value>An integer describing the total number of entities in the collection. The API might not be able to determine this value, in which case this property will not be present. </value>
        [DataMember(Name = "totalItems", EmitDefaultValue = false)]
        public long TotalItems { get; set; }

        /// <summary>
        /// An integer describing how many entities exist in the collection before those included in this list. 
        /// </summary>
        /// <value>An integer describing how many entities exist in the collection before those included in this list. </value>
        [DataMember(Name = "skipCount", EmitDefaultValue = false)]
        public long SkipCount { get; set; }

        /// <summary>
        /// The value of the **maxItems** parameter used to generate this list, or if there was no **maxItems** parameter the default value, 10 
        /// </summary>
        /// <value>The value of the **maxItems** parameter used to generate this list, or if there was no **maxItems** parameter the default value, 10 </value>
        [DataMember(Name = "maxItems", EmitDefaultValue = false)]
        public long MaxItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Pagination {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  HasMoreItems: ").Append(HasMoreItems).Append("\n");
            sb.Append("  TotalItems: ").Append(TotalItems).Append("\n");
            sb.Append("  SkipCount: ").Append(SkipCount).Append("\n");
            sb.Append("  MaxItems: ").Append(MaxItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Pagination);
        }

        /// <summary>
        /// Returns true if Pagination instances are equal
        /// </summary>
        /// <param name="input">Instance of Pagination to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Pagination input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Count == input.Count ||
                    this.Count.Equals(input.Count)
                ) && 
                (
                    this.HasMoreItems == input.HasMoreItems ||
                    this.HasMoreItems.Equals(input.HasMoreItems)
                ) && 
                (
                    this.TotalItems == input.TotalItems ||
                    this.TotalItems.Equals(input.TotalItems)
                ) && 
                (
                    this.SkipCount == input.SkipCount ||
                    this.SkipCount.Equals(input.SkipCount)
                ) && 
                (
                    this.MaxItems == input.MaxItems ||
                    this.MaxItems.Equals(input.MaxItems)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Count.GetHashCode();
                hashCode = (hashCode * 59) + this.HasMoreItems.GetHashCode();
                hashCode = (hashCode * 59) + this.TotalItems.GetHashCode();
                hashCode = (hashCode * 59) + this.SkipCount.GetHashCode();
                hashCode = (hashCode * 59) + this.MaxItems.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
