/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// Person
    /// </summary>
    [DataContract(Name = "Person")]
    public partial class Person : IEquatable<Person>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Person" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Person() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Person" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="firstName">firstName.</param>
        /// <param name="lastName">lastName.</param>
        /// <param name="description">description.</param>
        /// <param name="avatarId">avatarId.</param>
        /// <param name="email">email.</param>
        /// <param name="skypeId">skypeId.</param>
        /// <param name="googleId">googleId.</param>
        /// <param name="instantMessageId">instantMessageId.</param>
        /// <param name="jobTitle">jobTitle.</param>
        /// <param name="location">location.</param>
        /// <param name="company">company.</param>
        /// <param name="mobile">mobile.</param>
        /// <param name="telephone">telephone.</param>
        /// <param name="statusUpdatedAt">statusUpdatedAt.</param>
        /// <param name="userStatus">userStatus.</param>
        /// <param name="enabled">enabled (default to true).</param>
        /// <param name="emailNotificationsEnabled">emailNotificationsEnabled.</param>
        public Person(string id = default(string), string firstName = default(string), string lastName = default(string), string description = default(string), string avatarId = default(string), string email = default(string), string skypeId = default(string), string googleId = default(string), string instantMessageId = default(string), string jobTitle = default(string), string location = default(string), Company company = default(Company), string mobile = default(string), string telephone = default(string), DateTime statusUpdatedAt = default(DateTime), string userStatus = default(string), bool enabled = true, bool emailNotificationsEnabled = default(bool))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Person and cannot be null");
            }
            this.Id = id;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.Description = description;
            this.AvatarId = avatarId;
            this.Email = email;
            this.SkypeId = skypeId;
            this.GoogleId = googleId;
            this.InstantMessageId = instantMessageId;
            this.JobTitle = jobTitle;
            this.Location = location;
            this.Company = company;
            this.Mobile = mobile;
            this.Telephone = telephone;
            this.StatusUpdatedAt = statusUpdatedAt;
            this.UserStatus = userStatus;
            this.Enabled = enabled;
            this.EmailNotificationsEnabled = emailNotificationsEnabled;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "firstName", EmitDefaultValue = false)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "lastName", EmitDefaultValue = false)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets AvatarId
        /// </summary>
        [DataMember(Name = "avatarId", EmitDefaultValue = false)]
        public string AvatarId { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets SkypeId
        /// </summary>
        [DataMember(Name = "skypeId", EmitDefaultValue = false)]
        public string SkypeId { get; set; }

        /// <summary>
        /// Gets or Sets GoogleId
        /// </summary>
        [DataMember(Name = "googleId", EmitDefaultValue = false)]
        public string GoogleId { get; set; }

        /// <summary>
        /// Gets or Sets InstantMessageId
        /// </summary>
        [DataMember(Name = "instantMessageId", EmitDefaultValue = false)]
        public string InstantMessageId { get; set; }

        /// <summary>
        /// Gets or Sets JobTitle
        /// </summary>
        [DataMember(Name = "jobTitle", EmitDefaultValue = false)]
        public string JobTitle { get; set; }

        /// <summary>
        /// Gets or Sets Location
        /// </summary>
        [DataMember(Name = "location", EmitDefaultValue = false)]
        public string Location { get; set; }

        /// <summary>
        /// Gets or Sets Company
        /// </summary>
        [DataMember(Name = "company", EmitDefaultValue = false)]
        public Company Company { get; set; }

        /// <summary>
        /// Gets or Sets Mobile
        /// </summary>
        [DataMember(Name = "mobile", EmitDefaultValue = false)]
        public string Mobile { get; set; }

        /// <summary>
        /// Gets or Sets Telephone
        /// </summary>
        [DataMember(Name = "telephone", EmitDefaultValue = false)]
        public string Telephone { get; set; }

        /// <summary>
        /// Gets or Sets StatusUpdatedAt
        /// </summary>
        [DataMember(Name = "statusUpdatedAt", EmitDefaultValue = false)]
        public DateTime StatusUpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UserStatus
        /// </summary>
        [DataMember(Name = "userStatus", EmitDefaultValue = false)]
        public string UserStatus { get; set; }

        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name = "enabled", EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or Sets EmailNotificationsEnabled
        /// </summary>
        [DataMember(Name = "emailNotificationsEnabled", EmitDefaultValue = true)]
        public bool EmailNotificationsEnabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Person {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AvatarId: ").Append(AvatarId).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  SkypeId: ").Append(SkypeId).Append("\n");
            sb.Append("  GoogleId: ").Append(GoogleId).Append("\n");
            sb.Append("  InstantMessageId: ").Append(InstantMessageId).Append("\n");
            sb.Append("  JobTitle: ").Append(JobTitle).Append("\n");
            sb.Append("  Location: ").Append(Location).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Mobile: ").Append(Mobile).Append("\n");
            sb.Append("  Telephone: ").Append(Telephone).Append("\n");
            sb.Append("  StatusUpdatedAt: ").Append(StatusUpdatedAt).Append("\n");
            sb.Append("  UserStatus: ").Append(UserStatus).Append("\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  EmailNotificationsEnabled: ").Append(EmailNotificationsEnabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Person);
        }

        /// <summary>
        /// Returns true if Person instances are equal
        /// </summary>
        /// <param name="input">Instance of Person to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Person input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.AvatarId == input.AvatarId ||
                    (this.AvatarId != null &&
                    this.AvatarId.Equals(input.AvatarId))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.SkypeId == input.SkypeId ||
                    (this.SkypeId != null &&
                    this.SkypeId.Equals(input.SkypeId))
                ) && 
                (
                    this.GoogleId == input.GoogleId ||
                    (this.GoogleId != null &&
                    this.GoogleId.Equals(input.GoogleId))
                ) && 
                (
                    this.InstantMessageId == input.InstantMessageId ||
                    (this.InstantMessageId != null &&
                    this.InstantMessageId.Equals(input.InstantMessageId))
                ) && 
                (
                    this.JobTitle == input.JobTitle ||
                    (this.JobTitle != null &&
                    this.JobTitle.Equals(input.JobTitle))
                ) && 
                (
                    this.Location == input.Location ||
                    (this.Location != null &&
                    this.Location.Equals(input.Location))
                ) && 
                (
                    this.Company == input.Company ||
                    (this.Company != null &&
                    this.Company.Equals(input.Company))
                ) && 
                (
                    this.Mobile == input.Mobile ||
                    (this.Mobile != null &&
                    this.Mobile.Equals(input.Mobile))
                ) && 
                (
                    this.Telephone == input.Telephone ||
                    (this.Telephone != null &&
                    this.Telephone.Equals(input.Telephone))
                ) && 
                (
                    this.StatusUpdatedAt == input.StatusUpdatedAt ||
                    (this.StatusUpdatedAt != null &&
                    this.StatusUpdatedAt.Equals(input.StatusUpdatedAt))
                ) && 
                (
                    this.UserStatus == input.UserStatus ||
                    (this.UserStatus != null &&
                    this.UserStatus.Equals(input.UserStatus))
                ) && 
                (
                    this.Enabled == input.Enabled ||
                    this.Enabled.Equals(input.Enabled)
                ) && 
                (
                    this.EmailNotificationsEnabled == input.EmailNotificationsEnabled ||
                    this.EmailNotificationsEnabled.Equals(input.EmailNotificationsEnabled)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.FirstName != null)
                {
                    hashCode = (hashCode * 59) + this.FirstName.GetHashCode();
                }
                if (this.LastName != null)
                {
                    hashCode = (hashCode * 59) + this.LastName.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.AvatarId != null)
                {
                    hashCode = (hashCode * 59) + this.AvatarId.GetHashCode();
                }
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.SkypeId != null)
                {
                    hashCode = (hashCode * 59) + this.SkypeId.GetHashCode();
                }
                if (this.GoogleId != null)
                {
                    hashCode = (hashCode * 59) + this.GoogleId.GetHashCode();
                }
                if (this.InstantMessageId != null)
                {
                    hashCode = (hashCode * 59) + this.InstantMessageId.GetHashCode();
                }
                if (this.JobTitle != null)
                {
                    hashCode = (hashCode * 59) + this.JobTitle.GetHashCode();
                }
                if (this.Location != null)
                {
                    hashCode = (hashCode * 59) + this.Location.GetHashCode();
                }
                if (this.Company != null)
                {
                    hashCode = (hashCode * 59) + this.Company.GetHashCode();
                }
                if (this.Mobile != null)
                {
                    hashCode = (hashCode * 59) + this.Mobile.GetHashCode();
                }
                if (this.Telephone != null)
                {
                    hashCode = (hashCode * 59) + this.Telephone.GetHashCode();
                }
                if (this.StatusUpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StatusUpdatedAt.GetHashCode();
                }
                if (this.UserStatus != null)
                {
                    hashCode = (hashCode * 59) + this.UserStatus.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Enabled.GetHashCode();
                hashCode = (hashCode * 59) + this.EmailNotificationsEnabled.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
