/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A process describes a running instance of a process definition.  When a new deployment includes a process definition that is already deployed with the same key, the newly deployed process definition will be considered a new version of the same process definition. By default processes will keep running in the process definition they are started in. But new processes can be started in the latest version of a process definition by using the processDefinitionKey parameter.  In non-network deployments, administrators can see all processes and perform all operations on tasks. In network deployments, network administrators can see processes in their network and perform all operations on tasks in their network. 
    /// </summary>
    [DataContract(Name = "Process")]
    public partial class Process : IEquatable<Process>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Process" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Process() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Process" /> class.
        /// </summary>
        /// <param name="id">The unique id of this process (required).</param>
        /// <param name="processDefinitionId">The unique identity of the owning process definition.</param>
        /// <param name="businessKey">The business key.</param>
        /// <param name="startedAt">The date time this process started.</param>
        /// <param name="endedAt">The date time this process started.</param>
        /// <param name="durationInMs">The duration of this process.</param>
        /// <param name="startActivityDefinitionId">The id of the first activity in the process.</param>
        /// <param name="endActivityDefinitionId">The id of the last activity in the process.</param>
        /// <param name="startUserId">The id of the user who started the process.</param>
        /// <param name="deleteReason">The reason this process was canceled.</param>
        public Process(string id = default(string), string processDefinitionId = default(string), string businessKey = default(string), DateTime startedAt = default(DateTime), DateTime endedAt = default(DateTime), int durationInMs = default(int), string startActivityDefinitionId = default(string), string endActivityDefinitionId = default(string), string startUserId = default(string), string deleteReason = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Process and cannot be null");
            }
            this.Id = id;
            this.ProcessDefinitionId = processDefinitionId;
            this.BusinessKey = businessKey;
            this.StartedAt = startedAt;
            this.EndedAt = endedAt;
            this.DurationInMs = durationInMs;
            this.StartActivityDefinitionId = startActivityDefinitionId;
            this.EndActivityDefinitionId = endActivityDefinitionId;
            this.StartUserId = startUserId;
            this.DeleteReason = deleteReason;
        }

        /// <summary>
        /// The unique id of this process
        /// </summary>
        /// <value>The unique id of this process</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The unique identity of the owning process definition
        /// </summary>
        /// <value>The unique identity of the owning process definition</value>
        [DataMember(Name = "processDefinitionId", EmitDefaultValue = false)]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// The business key
        /// </summary>
        /// <value>The business key</value>
        [DataMember(Name = "businessKey", EmitDefaultValue = false)]
        public string BusinessKey { get; set; }

        /// <summary>
        /// The date time this process started
        /// </summary>
        /// <value>The date time this process started</value>
        [DataMember(Name = "startedAt", EmitDefaultValue = false)]
        public DateTime StartedAt { get; set; }

        /// <summary>
        /// The date time this process started
        /// </summary>
        /// <value>The date time this process started</value>
        [DataMember(Name = "endedAt", EmitDefaultValue = false)]
        public DateTime EndedAt { get; set; }

        /// <summary>
        /// The duration of this process
        /// </summary>
        /// <value>The duration of this process</value>
        [DataMember(Name = "durationInMs", EmitDefaultValue = false)]
        public int DurationInMs { get; set; }

        /// <summary>
        /// The id of the first activity in the process
        /// </summary>
        /// <value>The id of the first activity in the process</value>
        [DataMember(Name = "startActivityDefinitionId", EmitDefaultValue = false)]
        public string StartActivityDefinitionId { get; set; }

        /// <summary>
        /// The id of the last activity in the process
        /// </summary>
        /// <value>The id of the last activity in the process</value>
        [DataMember(Name = "endActivityDefinitionId", EmitDefaultValue = false)]
        public string EndActivityDefinitionId { get; set; }

        /// <summary>
        /// The id of the user who started the process
        /// </summary>
        /// <value>The id of the user who started the process</value>
        [DataMember(Name = "startUserId", EmitDefaultValue = false)]
        public string StartUserId { get; set; }

        /// <summary>
        /// The reason this process was canceled
        /// </summary>
        /// <value>The reason this process was canceled</value>
        [DataMember(Name = "deleteReason", EmitDefaultValue = false)]
        public string DeleteReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Process {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProcessDefinitionId: ").Append(ProcessDefinitionId).Append("\n");
            sb.Append("  BusinessKey: ").Append(BusinessKey).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  EndedAt: ").Append(EndedAt).Append("\n");
            sb.Append("  DurationInMs: ").Append(DurationInMs).Append("\n");
            sb.Append("  StartActivityDefinitionId: ").Append(StartActivityDefinitionId).Append("\n");
            sb.Append("  EndActivityDefinitionId: ").Append(EndActivityDefinitionId).Append("\n");
            sb.Append("  StartUserId: ").Append(StartUserId).Append("\n");
            sb.Append("  DeleteReason: ").Append(DeleteReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Process);
        }

        /// <summary>
        /// Returns true if Process instances are equal
        /// </summary>
        /// <param name="input">Instance of Process to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Process input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ProcessDefinitionId == input.ProcessDefinitionId ||
                    (this.ProcessDefinitionId != null &&
                    this.ProcessDefinitionId.Equals(input.ProcessDefinitionId))
                ) && 
                (
                    this.BusinessKey == input.BusinessKey ||
                    (this.BusinessKey != null &&
                    this.BusinessKey.Equals(input.BusinessKey))
                ) && 
                (
                    this.StartedAt == input.StartedAt ||
                    (this.StartedAt != null &&
                    this.StartedAt.Equals(input.StartedAt))
                ) && 
                (
                    this.EndedAt == input.EndedAt ||
                    (this.EndedAt != null &&
                    this.EndedAt.Equals(input.EndedAt))
                ) && 
                (
                    this.DurationInMs == input.DurationInMs ||
                    this.DurationInMs.Equals(input.DurationInMs)
                ) && 
                (
                    this.StartActivityDefinitionId == input.StartActivityDefinitionId ||
                    (this.StartActivityDefinitionId != null &&
                    this.StartActivityDefinitionId.Equals(input.StartActivityDefinitionId))
                ) && 
                (
                    this.EndActivityDefinitionId == input.EndActivityDefinitionId ||
                    (this.EndActivityDefinitionId != null &&
                    this.EndActivityDefinitionId.Equals(input.EndActivityDefinitionId))
                ) && 
                (
                    this.StartUserId == input.StartUserId ||
                    (this.StartUserId != null &&
                    this.StartUserId.Equals(input.StartUserId))
                ) && 
                (
                    this.DeleteReason == input.DeleteReason ||
                    (this.DeleteReason != null &&
                    this.DeleteReason.Equals(input.DeleteReason))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.ProcessDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.ProcessDefinitionId.GetHashCode();
                }
                if (this.BusinessKey != null)
                {
                    hashCode = (hashCode * 59) + this.BusinessKey.GetHashCode();
                }
                if (this.StartedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartedAt.GetHashCode();
                }
                if (this.EndedAt != null)
                {
                    hashCode = (hashCode * 59) + this.EndedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DurationInMs.GetHashCode();
                if (this.StartActivityDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.StartActivityDefinitionId.GetHashCode();
                }
                if (this.EndActivityDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.EndActivityDefinitionId.GetHashCode();
                }
                if (this.StartUserId != null)
                {
                    hashCode = (hashCode * 59) + this.StartUserId.GetHashCode();
                }
                if (this.DeleteReason != null)
                {
                    hashCode = (hashCode * 59) + this.DeleteReason.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
