/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A process definition is a description of an execution flow in terms of activities. New processes are created and started for a process definition. 
    /// </summary>
    [DataContract(Name = "ProcessDefinition")]
    public partial class ProcessDefinition : IEquatable<ProcessDefinition>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProcessDefinition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinition" /> class.
        /// </summary>
        /// <param name="id">The unique id of this process definition (required).</param>
        /// <param name="key">The key of this process definition.</param>
        /// <param name="name">The name of this process definition.</param>
        /// <param name="category">The category to which this process definition belongs.</param>
        /// <param name="deploymentId">The deployment of which this process definition is a part.</param>
        /// <param name="title">The title of this process definition.</param>
        /// <param name="description">The description of this process definition.</param>
        /// <param name="startFormResourceKey">The start form key.</param>
        /// <param name="graphicNotationDefined">graphicNotationDefined.</param>
        public ProcessDefinition(string id = default(string), string key = default(string), string name = default(string), string category = default(string), string deploymentId = default(string), string title = default(string), string description = default(string), string startFormResourceKey = default(string), bool graphicNotationDefined = default(bool))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ProcessDefinition and cannot be null");
            }
            this.Id = id;
            this.Key = key;
            this.Name = name;
            this.Category = category;
            this.DeploymentId = deploymentId;
            this.Title = title;
            this.Description = description;
            this.StartFormResourceKey = startFormResourceKey;
            this.GraphicNotationDefined = graphicNotationDefined;
        }

        /// <summary>
        /// The unique id of this process definition
        /// </summary>
        /// <value>The unique id of this process definition</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The key of this process definition
        /// </summary>
        /// <value>The key of this process definition</value>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// The name of this process definition
        /// </summary>
        /// <value>The name of this process definition</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The category to which this process definition belongs
        /// </summary>
        /// <value>The category to which this process definition belongs</value>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public string Category { get; set; }

        /// <summary>
        /// The deployment of which this process definition is a part
        /// </summary>
        /// <value>The deployment of which this process definition is a part</value>
        [DataMember(Name = "deploymentId", EmitDefaultValue = false)]
        public string DeploymentId { get; set; }

        /// <summary>
        /// The title of this process definition
        /// </summary>
        /// <value>The title of this process definition</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// The description of this process definition
        /// </summary>
        /// <value>The description of this process definition</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The start form key
        /// </summary>
        /// <value>The start form key</value>
        [DataMember(Name = "startFormResourceKey", EmitDefaultValue = false)]
        public string StartFormResourceKey { get; set; }

        /// <summary>
        /// Gets or Sets GraphicNotationDefined
        /// </summary>
        [DataMember(Name = "graphicNotationDefined", EmitDefaultValue = true)]
        public bool GraphicNotationDefined { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessDefinition {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  DeploymentId: ").Append(DeploymentId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  StartFormResourceKey: ").Append(StartFormResourceKey).Append("\n");
            sb.Append("  GraphicNotationDefined: ").Append(GraphicNotationDefined).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessDefinition);
        }

        /// <summary>
        /// Returns true if ProcessDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessDefinition input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Category == input.Category ||
                    (this.Category != null &&
                    this.Category.Equals(input.Category))
                ) && 
                (
                    this.DeploymentId == input.DeploymentId ||
                    (this.DeploymentId != null &&
                    this.DeploymentId.Equals(input.DeploymentId))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.StartFormResourceKey == input.StartFormResourceKey ||
                    (this.StartFormResourceKey != null &&
                    this.StartFormResourceKey.Equals(input.StartFormResourceKey))
                ) && 
                (
                    this.GraphicNotationDefined == input.GraphicNotationDefined ||
                    this.GraphicNotationDefined.Equals(input.GraphicNotationDefined)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Key != null)
                {
                    hashCode = (hashCode * 59) + this.Key.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Category != null)
                {
                    hashCode = (hashCode * 59) + this.Category.GetHashCode();
                }
                if (this.DeploymentId != null)
                {
                    hashCode = (hashCode * 59) + this.DeploymentId.GetHashCode();
                }
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.StartFormResourceKey != null)
                {
                    hashCode = (hashCode * 59) + this.StartFormResourceKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.GraphicNotationDefined.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
