/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A set of process variables of differing types. 
    /// </summary>
    [DataContract(Name = "ProcessBodyVariable")]
    public partial class ProcessBodyVariable : IEquatable<ProcessBodyVariable>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessBodyVariable" /> class.
        /// </summary>
        /// <param name="bpmAssignee">bpmAssignee.</param>
        /// <param name="bpmSendEMailNotifications">bpmSendEMailNotifications.</param>
        /// <param name="bpmWorkflowPriority">bpmWorkflowPriority.</param>
        public ProcessBodyVariable(string bpmAssignee = default(string), bool bpmSendEMailNotifications = default(bool), int bpmWorkflowPriority = default(int))
        {
            this.BpmAssignee = bpmAssignee;
            this.BpmSendEMailNotifications = bpmSendEMailNotifications;
            this.BpmWorkflowPriority = bpmWorkflowPriority;
        }

        /// <summary>
        /// Gets or Sets BpmAssignee
        /// </summary>
        [DataMember(Name = "bpm_assignee", EmitDefaultValue = false)]
        public string BpmAssignee { get; set; }

        /// <summary>
        /// Gets or Sets BpmSendEMailNotifications
        /// </summary>
        [DataMember(Name = "bpm_sendEMailNotifications", EmitDefaultValue = true)]
        public bool BpmSendEMailNotifications { get; set; }

        /// <summary>
        /// Gets or Sets BpmWorkflowPriority
        /// </summary>
        [DataMember(Name = "bpm_workflowPriority", EmitDefaultValue = false)]
        public int BpmWorkflowPriority { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessBodyVariable {\n");
            sb.Append("  BpmAssignee: ").Append(BpmAssignee).Append("\n");
            sb.Append("  BpmSendEMailNotifications: ").Append(BpmSendEMailNotifications).Append("\n");
            sb.Append("  BpmWorkflowPriority: ").Append(BpmWorkflowPriority).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProcessBodyVariable);
        }

        /// <summary>
        /// Returns true if ProcessBodyVariable instances are equal
        /// </summary>
        /// <param name="input">Instance of ProcessBodyVariable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProcessBodyVariable input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.BpmAssignee == input.BpmAssignee ||
                    (this.BpmAssignee != null &&
                    this.BpmAssignee.Equals(input.BpmAssignee))
                ) && 
                (
                    this.BpmSendEMailNotifications == input.BpmSendEMailNotifications ||
                    this.BpmSendEMailNotifications.Equals(input.BpmSendEMailNotifications)
                ) && 
                (
                    this.BpmWorkflowPriority == input.BpmWorkflowPriority ||
                    this.BpmWorkflowPriority.Equals(input.BpmWorkflowPriority)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BpmAssignee != null)
                {
                    hashCode = (hashCode * 59) + this.BpmAssignee.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.BpmSendEMailNotifications.GetHashCode();
                hashCode = (hashCode * 59) + this.BpmWorkflowPriority.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
