/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A task describes one task for a human user. 
    /// </summary>
    [DataContract(Name = "Task")]
    public partial class Task : IEquatable<Task>, IValidatableObject
    {
        /// <summary>
        /// The state of this task
        /// </summary>
        /// <value>The state of this task</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Unclaimed for value: unclaimed
            /// </summary>
            [EnumMember(Value = "unclaimed")]
            Unclaimed = 1,

            /// <summary>
            /// Enum Claimed for value: claimed
            /// </summary>
            [EnumMember(Value = "claimed")]
            Claimed = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Resolved for value: resolved
            /// </summary>
            [EnumMember(Value = "resolved")]
            Resolved = 4

        }


        /// <summary>
        /// The state of this task
        /// </summary>
        /// <value>The state of this task</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Task" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Task() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Task" /> class.
        /// </summary>
        /// <param name="id">The unique id of this task (required).</param>
        /// <param name="processId">The containing process&#39;s unique id.</param>
        /// <param name="processDefinitionId">The unique identity of the owning process definition.</param>
        /// <param name="activityDefinitionId">The activity id of this task.</param>
        /// <param name="name">The text name of this task.</param>
        /// <param name="description">The description of this task.</param>
        /// <param name="dueAt">The date time this task is due.</param>
        /// <param name="startedAt">The date time this task started.</param>
        /// <param name="endedAt">The date time this task started.</param>
        /// <param name="durationInMs">The duration of this task.</param>
        /// <param name="priority">The numeric priority of this task.</param>
        /// <param name="owner">The id of the user who owns this task.</param>
        /// <param name="assignee">The id of the user who is currently assigned this task.</param>
        /// <param name="formResourceKey">The key of the form for this task.</param>
        /// <param name="state">The state of this task.</param>
        /// <param name="variables">An array of variables for this task.</param>
        public Task(string id = default(string), string processId = default(string), string processDefinitionId = default(string), string activityDefinitionId = default(string), string name = default(string), string description = default(string), DateTime dueAt = default(DateTime), DateTime startedAt = default(DateTime), DateTime endedAt = default(DateTime), int durationInMs = default(int), int priority = default(int), string owner = default(string), string assignee = default(string), string formResourceKey = default(string), StateEnum? state = default(StateEnum?), List<Variable> variables = default(List<Variable>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Task and cannot be null");
            }
            this.Id = id;
            this.ProcessId = processId;
            this.ProcessDefinitionId = processDefinitionId;
            this.ActivityDefinitionId = activityDefinitionId;
            this.Name = name;
            this.Description = description;
            this.DueAt = dueAt;
            this.StartedAt = startedAt;
            this.EndedAt = endedAt;
            this.DurationInMs = durationInMs;
            this.Priority = priority;
            this.Owner = owner;
            this.Assignee = assignee;
            this.FormResourceKey = formResourceKey;
            this.State = state;
            this.Variables = variables;
        }

        /// <summary>
        /// The unique id of this task
        /// </summary>
        /// <value>The unique id of this task</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The containing process&#39;s unique id
        /// </summary>
        /// <value>The containing process&#39;s unique id</value>
        [DataMember(Name = "processId", EmitDefaultValue = false)]
        public string ProcessId { get; set; }

        /// <summary>
        /// The unique identity of the owning process definition
        /// </summary>
        /// <value>The unique identity of the owning process definition</value>
        [DataMember(Name = "processDefinitionId", EmitDefaultValue = false)]
        public string ProcessDefinitionId { get; set; }

        /// <summary>
        /// The activity id of this task
        /// </summary>
        /// <value>The activity id of this task</value>
        [DataMember(Name = "activityDefinitionId", EmitDefaultValue = false)]
        public string ActivityDefinitionId { get; set; }

        /// <summary>
        /// The text name of this task
        /// </summary>
        /// <value>The text name of this task</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The description of this task
        /// </summary>
        /// <value>The description of this task</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The date time this task is due
        /// </summary>
        /// <value>The date time this task is due</value>
        [DataMember(Name = "dueAt", EmitDefaultValue = false)]
        public DateTime DueAt { get; set; }

        /// <summary>
        /// The date time this task started
        /// </summary>
        /// <value>The date time this task started</value>
        [DataMember(Name = "startedAt", EmitDefaultValue = false)]
        public DateTime StartedAt { get; set; }

        /// <summary>
        /// The date time this task started
        /// </summary>
        /// <value>The date time this task started</value>
        [DataMember(Name = "endedAt", EmitDefaultValue = false)]
        public DateTime EndedAt { get; set; }

        /// <summary>
        /// The duration of this task
        /// </summary>
        /// <value>The duration of this task</value>
        [DataMember(Name = "durationInMs", EmitDefaultValue = false)]
        public int DurationInMs { get; set; }

        /// <summary>
        /// The numeric priority of this task
        /// </summary>
        /// <value>The numeric priority of this task</value>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public int Priority { get; set; }

        /// <summary>
        /// The id of the user who owns this task
        /// </summary>
        /// <value>The id of the user who owns this task</value>
        [DataMember(Name = "owner", EmitDefaultValue = false)]
        public string Owner { get; set; }

        /// <summary>
        /// The id of the user who is currently assigned this task
        /// </summary>
        /// <value>The id of the user who is currently assigned this task</value>
        [DataMember(Name = "assignee", EmitDefaultValue = false)]
        public string Assignee { get; set; }

        /// <summary>
        /// The key of the form for this task
        /// </summary>
        /// <value>The key of the form for this task</value>
        [DataMember(Name = "formResourceKey", EmitDefaultValue = false)]
        public string FormResourceKey { get; set; }

        /// <summary>
        /// An array of variables for this task
        /// </summary>
        /// <value>An array of variables for this task</value>
        [DataMember(Name = "variables", EmitDefaultValue = false)]
        public List<Variable> Variables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Task {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProcessId: ").Append(ProcessId).Append("\n");
            sb.Append("  ProcessDefinitionId: ").Append(ProcessDefinitionId).Append("\n");
            sb.Append("  ActivityDefinitionId: ").Append(ActivityDefinitionId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DueAt: ").Append(DueAt).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  EndedAt: ").Append(EndedAt).Append("\n");
            sb.Append("  DurationInMs: ").Append(DurationInMs).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Assignee: ").Append(Assignee).Append("\n");
            sb.Append("  FormResourceKey: ").Append(FormResourceKey).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Task);
        }

        /// <summary>
        /// Returns true if Task instances are equal
        /// </summary>
        /// <param name="input">Instance of Task to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Task input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ProcessId == input.ProcessId ||
                    (this.ProcessId != null &&
                    this.ProcessId.Equals(input.ProcessId))
                ) && 
                (
                    this.ProcessDefinitionId == input.ProcessDefinitionId ||
                    (this.ProcessDefinitionId != null &&
                    this.ProcessDefinitionId.Equals(input.ProcessDefinitionId))
                ) && 
                (
                    this.ActivityDefinitionId == input.ActivityDefinitionId ||
                    (this.ActivityDefinitionId != null &&
                    this.ActivityDefinitionId.Equals(input.ActivityDefinitionId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DueAt == input.DueAt ||
                    (this.DueAt != null &&
                    this.DueAt.Equals(input.DueAt))
                ) && 
                (
                    this.StartedAt == input.StartedAt ||
                    (this.StartedAt != null &&
                    this.StartedAt.Equals(input.StartedAt))
                ) && 
                (
                    this.EndedAt == input.EndedAt ||
                    (this.EndedAt != null &&
                    this.EndedAt.Equals(input.EndedAt))
                ) && 
                (
                    this.DurationInMs == input.DurationInMs ||
                    this.DurationInMs.Equals(input.DurationInMs)
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.Assignee == input.Assignee ||
                    (this.Assignee != null &&
                    this.Assignee.Equals(input.Assignee))
                ) && 
                (
                    this.FormResourceKey == input.FormResourceKey ||
                    (this.FormResourceKey != null &&
                    this.FormResourceKey.Equals(input.FormResourceKey))
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.Variables == input.Variables ||
                    this.Variables != null &&
                    input.Variables != null &&
                    this.Variables.SequenceEqual(input.Variables)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.ProcessId != null)
                {
                    hashCode = (hashCode * 59) + this.ProcessId.GetHashCode();
                }
                if (this.ProcessDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.ProcessDefinitionId.GetHashCode();
                }
                if (this.ActivityDefinitionId != null)
                {
                    hashCode = (hashCode * 59) + this.ActivityDefinitionId.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.DueAt != null)
                {
                    hashCode = (hashCode * 59) + this.DueAt.GetHashCode();
                }
                if (this.StartedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartedAt.GetHashCode();
                }
                if (this.EndedAt != null)
                {
                    hashCode = (hashCode * 59) + this.EndedAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DurationInMs.GetHashCode();
                hashCode = (hashCode * 59) + this.Priority.GetHashCode();
                if (this.Owner != null)
                {
                    hashCode = (hashCode * 59) + this.Owner.GetHashCode();
                }
                if (this.Assignee != null)
                {
                    hashCode = (hashCode * 59) + this.Assignee.GetHashCode();
                }
                if (this.FormResourceKey != null)
                {
                    hashCode = (hashCode * 59) + this.FormResourceKey.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                if (this.Variables != null)
                {
                    hashCode = (hashCode * 59) + this.Variables.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
