/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// A task form model item. 
    /// </summary>
    [DataContract(Name = "TaskFormModel")]
    public partial class TaskFormModel : IEquatable<TaskFormModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskFormModel" /> class.
        /// </summary>
        /// <param name="dataType">dataType.</param>
        /// <param name="title">title.</param>
        /// <param name="qualifiedName">qualifiedName.</param>
        /// <param name="name">name.</param>
        /// <param name="required">required.</param>
        /// <param name="defaultValue">defaultValue.</param>
        /// <param name="allowedValues">An array of allowed values for this item.</param>
        public TaskFormModel(string dataType = default(string), string title = default(string), string qualifiedName = default(string), string name = default(string), bool required = default(bool), string defaultValue = default(string), List<string> allowedValues = default(List<string>))
        {
            this.DataType = dataType;
            this.Title = title;
            this.QualifiedName = qualifiedName;
            this.Name = name;
            this.Required = required;
            this.DefaultValue = defaultValue;
            this.AllowedValues = allowedValues;
        }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "dataType", EmitDefaultValue = false)]
        public string DataType { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets QualifiedName
        /// </summary>
        [DataMember(Name = "qualifiedName", EmitDefaultValue = false)]
        public string QualifiedName { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Required
        /// </summary>
        [DataMember(Name = "required", EmitDefaultValue = true)]
        public bool Required { get; set; }

        /// <summary>
        /// Gets or Sets DefaultValue
        /// </summary>
        [DataMember(Name = "defaultValue", EmitDefaultValue = false)]
        public string DefaultValue { get; set; }

        /// <summary>
        /// An array of allowed values for this item
        /// </summary>
        /// <value>An array of allowed values for this item</value>
        [DataMember(Name = "allowedValues", EmitDefaultValue = false)]
        public List<string> AllowedValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskFormModel {\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  QualifiedName: ").Append(QualifiedName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Required: ").Append(Required).Append("\n");
            sb.Append("  DefaultValue: ").Append(DefaultValue).Append("\n");
            sb.Append("  AllowedValues: ").Append(AllowedValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaskFormModel);
        }

        /// <summary>
        /// Returns true if TaskFormModel instances are equal
        /// </summary>
        /// <param name="input">Instance of TaskFormModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskFormModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DataType == input.DataType ||
                    (this.DataType != null &&
                    this.DataType.Equals(input.DataType))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.QualifiedName == input.QualifiedName ||
                    (this.QualifiedName != null &&
                    this.QualifiedName.Equals(input.QualifiedName))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Required == input.Required ||
                    this.Required.Equals(input.Required)
                ) && 
                (
                    this.DefaultValue == input.DefaultValue ||
                    (this.DefaultValue != null &&
                    this.DefaultValue.Equals(input.DefaultValue))
                ) && 
                (
                    this.AllowedValues == input.AllowedValues ||
                    this.AllowedValues != null &&
                    input.AllowedValues != null &&
                    this.AllowedValues.SequenceEqual(input.AllowedValues)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DataType != null)
                {
                    hashCode = (hashCode * 59) + this.DataType.GetHashCode();
                }
                if (this.Title != null)
                {
                    hashCode = (hashCode * 59) + this.Title.GetHashCode();
                }
                if (this.QualifiedName != null)
                {
                    hashCode = (hashCode * 59) + this.QualifiedName.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Required.GetHashCode();
                if (this.DefaultValue != null)
                {
                    hashCode = (hashCode * 59) + this.DefaultValue.GetHashCode();
                }
                if (this.AllowedValues != null)
                {
                    hashCode = (hashCode * 59) + this.AllowedValues.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
