/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Variograma.AlfrescoWorkflow.Client.OpenAPIDateConverter;

namespace Variograma.AlfrescoWorkflow.Model
{
    /// <summary>
    /// Input body to update a specific task. 
    /// </summary>
    [DataContract(Name = "TaskBody")]
    public partial class TaskBody : IEquatable<TaskBody>, IValidatableObject
    {
        /// <summary>
        /// The state of this task
        /// </summary>
        /// <value>The state of this task</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Unclaimed for value: unclaimed
            /// </summary>
            [EnumMember(Value = "unclaimed")]
            Unclaimed = 1,

            /// <summary>
            /// Enum Claimed for value: claimed
            /// </summary>
            [EnumMember(Value = "claimed")]
            Claimed = 2,

            /// <summary>
            /// Enum Completed for value: completed
            /// </summary>
            [EnumMember(Value = "completed")]
            Completed = 3,

            /// <summary>
            /// Enum Resolved for value: resolved
            /// </summary>
            [EnumMember(Value = "resolved")]
            Resolved = 4

        }


        /// <summary>
        /// The state of this task
        /// </summary>
        /// <value>The state of this task</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskBody" /> class.
        /// </summary>
        /// <param name="name">The text name of this task.</param>
        /// <param name="description">The description of this task.</param>
        /// <param name="dueAt">The date time this task is due.</param>
        /// <param name="priority">The numeric priority of this task.</param>
        /// <param name="owner">The id of the user who owns this task.</param>
        /// <param name="state">The state of this task.</param>
        /// <param name="variables">An array of variables for this task.</param>
        public TaskBody(string name = default(string), string description = default(string), DateTime dueAt = default(DateTime), int priority = default(int), string owner = default(string), StateEnum? state = default(StateEnum?), List<Variable> variables = default(List<Variable>))
        {
            this.Name = name;
            this.Description = description;
            this.DueAt = dueAt;
            this.Priority = priority;
            this.Owner = owner;
            this.State = state;
            this.Variables = variables;
        }

        /// <summary>
        /// The text name of this task
        /// </summary>
        /// <value>The text name of this task</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// The description of this task
        /// </summary>
        /// <value>The description of this task</value>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The date time this task is due
        /// </summary>
        /// <value>The date time this task is due</value>
        [DataMember(Name = "dueAt", EmitDefaultValue = false)]
        public DateTime DueAt { get; set; }

        /// <summary>
        /// The numeric priority of this task
        /// </summary>
        /// <value>The numeric priority of this task</value>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public int Priority { get; set; }

        /// <summary>
        /// The id of the user who owns this task
        /// </summary>
        /// <value>The id of the user who owns this task</value>
        [DataMember(Name = "owner", EmitDefaultValue = false)]
        public string Owner { get; set; }

        /// <summary>
        /// An array of variables for this task
        /// </summary>
        /// <value>An array of variables for this task</value>
        [DataMember(Name = "variables", EmitDefaultValue = false)]
        public List<Variable> Variables { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskBody {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DueAt: ").Append(DueAt).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Variables: ").Append(Variables).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaskBody);
        }

        /// <summary>
        /// Returns true if TaskBody instances are equal
        /// </summary>
        /// <param name="input">Instance of TaskBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskBody input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.DueAt == input.DueAt ||
                    (this.DueAt != null &&
                    this.DueAt.Equals(input.DueAt))
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.Variables == input.Variables ||
                    this.Variables != null &&
                    input.Variables != null &&
                    this.Variables.SequenceEqual(input.Variables)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.DueAt != null)
                {
                    hashCode = (hashCode * 59) + this.DueAt.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Priority.GetHashCode();
                if (this.Owner != null)
                {
                    hashCode = (hashCode * 59) + this.Owner.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                if (this.Variables != null)
                {
                    hashCode = (hashCode * 59) + this.Variables.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
