/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeploymentsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a deployment
        /// </summary>
        /// <remarks>
        /// This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteDeployment(string deploymentId, int operationIndex = 0);

        /// <summary>
        /// Delete a deployment
        /// </summary>
        /// <remarks>
        /// This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteDeploymentWithHttpInfo(string deploymentId, int operationIndex = 0);
        /// <summary>
        /// Get a deployment
        /// </summary>
        /// <remarks>
        /// Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeploymentEntry</returns>
        DeploymentEntry GetDeployment(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// Get a deployment
        /// </summary>
        /// <remarks>
        /// Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeploymentEntry</returns>
        ApiResponse<DeploymentEntry> GetDeploymentWithHttpInfo(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// List deployments
        /// </summary>
        /// <remarks>
        /// Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeploymentPaging</returns>
        DeploymentPaging ListDeployments(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// List deployments
        /// </summary>
        /// <remarks>
        /// Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeploymentPaging</returns>
        ApiResponse<DeploymentPaging> ListDeploymentsWithHttpInfo(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeploymentsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete a deployment
        /// </summary>
        /// <remarks>
        /// This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteDeploymentAsync(string deploymentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a deployment
        /// </summary>
        /// <remarks>
        /// This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteDeploymentWithHttpInfoAsync(string deploymentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get a deployment
        /// </summary>
        /// <remarks>
        /// Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeploymentEntry</returns>
        System.Threading.Tasks.Task<DeploymentEntry> GetDeploymentAsync(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a deployment
        /// </summary>
        /// <remarks>
        /// Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeploymentEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeploymentEntry>> GetDeploymentWithHttpInfoAsync(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List deployments
        /// </summary>
        /// <remarks>
        /// Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeploymentPaging</returns>
        System.Threading.Tasks.Task<DeploymentPaging> ListDeploymentsAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List deployments
        /// </summary>
        /// <remarks>
        /// Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeploymentPaging)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeploymentPaging>> ListDeploymentsWithHttpInfoAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDeploymentsApi : IDeploymentsApiSync, IDeploymentsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DeploymentsApi : IDeploymentsApi
    {
        private Variograma.AlfrescoWorkflow.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeploymentsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DeploymentsApi(string basePath)
        {
            this.Configuration = Variograma.AlfrescoWorkflow.Client.Configuration.MergeConfigurations(
                Variograma.AlfrescoWorkflow.Client.GlobalConfiguration.Instance,
                new Variograma.AlfrescoWorkflow.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DeploymentsApi(Variograma.AlfrescoWorkflow.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Variograma.AlfrescoWorkflow.Client.Configuration.MergeConfigurations(
                Variograma.AlfrescoWorkflow.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeploymentsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DeploymentsApi(Variograma.AlfrescoWorkflow.Client.ISynchronousClient client, Variograma.AlfrescoWorkflow.Client.IAsynchronousClient asyncClient, Variograma.AlfrescoWorkflow.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Variograma.AlfrescoWorkflow.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete a deployment This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteDeployment(string deploymentId, int operationIndex = 0)
        {
            DeleteDeploymentWithHttpInfo(deploymentId);
        }

        /// <summary>
        /// Delete a deployment This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<Object> DeleteDeploymentWithHttpInfo(string deploymentId, int operationIndex = 0)
        {
            // verify the required parameter 'deploymentId' is set
            if (deploymentId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'deploymentId' when calling DeploymentsApi->DeleteDeployment");
            }

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("deploymentId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(deploymentId)); // path parameter

            localVarRequestOptions.Operation = "DeploymentsApi.DeleteDeployment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/deployments/{deploymentId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDeployment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a deployment This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteDeploymentAsync(string deploymentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteDeploymentWithHttpInfoAsync(deploymentId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete a deployment This request will delete the deployment including the tasks, process definitions contained in the deployment.  The request will also delete processes and history information associated with the deployment. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<Object>> DeleteDeploymentWithHttpInfoAsync(string deploymentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'deploymentId' is set
            if (deploymentId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'deploymentId' when calling DeploymentsApi->DeleteDeployment");
            }


            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("deploymentId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(deploymentId)); // path parameter

            localVarRequestOptions.Operation = "DeploymentsApi.DeleteDeployment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/deployments/{deploymentId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDeployment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a deployment Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeploymentEntry</returns>
        public DeploymentEntry GetDeployment(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentEntry> localVarResponse = GetDeploymentWithHttpInfo(deploymentId, properties);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a deployment Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeploymentEntry</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentEntry> GetDeploymentWithHttpInfo(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            // verify the required parameter 'deploymentId' is set
            if (deploymentId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'deploymentId' when calling DeploymentsApi->GetDeployment");
            }

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("deploymentId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(deploymentId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "DeploymentsApi.GetDeployment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DeploymentEntry>("/deployments/{deploymentId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDeployment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a deployment Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeploymentEntry</returns>
        public async System.Threading.Tasks.Task<DeploymentEntry> GetDeploymentAsync(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentEntry> localVarResponse = await GetDeploymentWithHttpInfoAsync(deploymentId, properties, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a deployment Gets a specified deployment defined by **deploymentId**.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the deployment is only returned if the deployment is in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="deploymentId">The unique id must be a String. It is returned as an **id** from the entity.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeploymentEntry)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentEntry>> GetDeploymentWithHttpInfoAsync(string deploymentId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'deploymentId' is set
            if (deploymentId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'deploymentId' when calling DeploymentsApi->GetDeployment");
            }


            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("deploymentId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(deploymentId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "DeploymentsApi.GetDeployment";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DeploymentEntry>("/deployments/{deploymentId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetDeployment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List deployments Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DeploymentPaging</returns>
        public DeploymentPaging ListDeployments(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentPaging> localVarResponse = ListDeploymentsWithHttpInfo(skipCount, maxItems, properties);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List deployments Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DeploymentPaging</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentPaging> ListDeploymentsWithHttpInfo(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (skipCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "skipCount", skipCount));
            }
            if (maxItems != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "maxItems", maxItems));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "DeploymentsApi.ListDeployments";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DeploymentPaging>("/deployments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDeployments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List deployments Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeploymentPaging</returns>
        public async System.Threading.Tasks.Task<DeploymentPaging> ListDeploymentsAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentPaging> localVarResponse = await ListDeploymentsWithHttpInfoAsync(skipCount, maxItems, properties, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List deployments Gets a list of deployments.  The authenticated user must have role admin (non-network deployments) or network admin (networks enabled).  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeploymentPaging)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<DeploymentPaging>> ListDeploymentsWithHttpInfoAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (skipCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "skipCount", skipCount));
            }
            if (maxItems != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "maxItems", maxItems));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "DeploymentsApi.ListDeployments";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DeploymentPaging>("/deployments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDeployments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
