/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProcessDefinitionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a process definition
        /// </summary>
        /// <remarks>
        /// Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProcessDefinitionEntry</returns>
        ProcessDefinitionEntry GetProcessDefinition(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// Get a process definition
        /// </summary>
        /// <remarks>
        /// Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProcessDefinitionEntry</returns>
        ApiResponse<ProcessDefinitionEntry> GetProcessDefinitionWithHttpInfo(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// Get a process definition image
        /// </summary>
        /// <remarks>
        /// Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetProcessDefinitionImage(string processDefinitionId, int operationIndex = 0);

        /// <summary>
        /// Get a process definition image
        /// </summary>
        /// <remarks>
        /// Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetProcessDefinitionImageWithHttpInfo(string processDefinitionId, int operationIndex = 0);
        /// <summary>
        /// Get a start form model
        /// </summary>
        /// <remarks>
        /// Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaskFormModelPaging</returns>
        TaskFormModelPaging GetProcessDefinitionStartFormModel(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// Get a start form model
        /// </summary>
        /// <remarks>
        /// Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaskFormModelPaging</returns>
        ApiResponse<TaskFormModelPaging> GetProcessDefinitionStartFormModelWithHttpInfo(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// List process definitions
        /// </summary>
        /// <remarks>
        /// Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProcessDefinitionPaging</returns>
        ProcessDefinitionPaging ListProcessDefinitions(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0);

        /// <summary>
        /// List process definitions
        /// </summary>
        /// <remarks>
        /// Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProcessDefinitionPaging</returns>
        ApiResponse<ProcessDefinitionPaging> ListProcessDefinitionsWithHttpInfo(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProcessDefinitionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get a process definition
        /// </summary>
        /// <remarks>
        /// Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProcessDefinitionEntry</returns>
        System.Threading.Tasks.Task<ProcessDefinitionEntry> GetProcessDefinitionAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a process definition
        /// </summary>
        /// <remarks>
        /// Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProcessDefinitionEntry)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProcessDefinitionEntry>> GetProcessDefinitionWithHttpInfoAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get a process definition image
        /// </summary>
        /// <remarks>
        /// Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetProcessDefinitionImageAsync(string processDefinitionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a process definition image
        /// </summary>
        /// <remarks>
        /// Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetProcessDefinitionImageWithHttpInfoAsync(string processDefinitionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get a start form model
        /// </summary>
        /// <remarks>
        /// Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaskFormModelPaging</returns>
        System.Threading.Tasks.Task<TaskFormModelPaging> GetProcessDefinitionStartFormModelAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a start form model
        /// </summary>
        /// <remarks>
        /// Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaskFormModelPaging)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaskFormModelPaging>> GetProcessDefinitionStartFormModelWithHttpInfoAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List process definitions
        /// </summary>
        /// <remarks>
        /// Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProcessDefinitionPaging</returns>
        System.Threading.Tasks.Task<ProcessDefinitionPaging> ListProcessDefinitionsAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List process definitions
        /// </summary>
        /// <remarks>
        /// Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </remarks>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProcessDefinitionPaging)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProcessDefinitionPaging>> ListProcessDefinitionsWithHttpInfoAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProcessDefinitionsApi : IProcessDefinitionsApiSync, IProcessDefinitionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProcessDefinitionsApi : IProcessDefinitionsApi
    {
        private Variograma.AlfrescoWorkflow.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinitionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProcessDefinitionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinitionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ProcessDefinitionsApi(string basePath)
        {
            this.Configuration = Variograma.AlfrescoWorkflow.Client.Configuration.MergeConfigurations(
                Variograma.AlfrescoWorkflow.Client.GlobalConfiguration.Instance,
                new Variograma.AlfrescoWorkflow.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinitionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ProcessDefinitionsApi(Variograma.AlfrescoWorkflow.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Variograma.AlfrescoWorkflow.Client.Configuration.MergeConfigurations(
                Variograma.AlfrescoWorkflow.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Variograma.AlfrescoWorkflow.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessDefinitionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ProcessDefinitionsApi(Variograma.AlfrescoWorkflow.Client.ISynchronousClient client, Variograma.AlfrescoWorkflow.Client.IAsynchronousClient asyncClient, Variograma.AlfrescoWorkflow.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Variograma.AlfrescoWorkflow.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Variograma.AlfrescoWorkflow.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Variograma.AlfrescoWorkflow.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get a process definition Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProcessDefinitionEntry</returns>
        public ProcessDefinitionEntry GetProcessDefinition(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionEntry> localVarResponse = GetProcessDefinitionWithHttpInfo(processDefinitionId, properties);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a process definition Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProcessDefinitionEntry</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionEntry> GetProcessDefinitionWithHttpInfo(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinition");
            }

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ProcessDefinitionEntry>("/process-definitions/{processDefinitionId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a process definition Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProcessDefinitionEntry</returns>
        public async System.Threading.Tasks.Task<ProcessDefinitionEntry> GetProcessDefinitionAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionEntry> localVarResponse = await GetProcessDefinitionWithHttpInfoAsync(processDefinitionId, properties, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a process definition Gets a process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions. If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProcessDefinitionEntry)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionEntry>> GetProcessDefinitionWithHttpInfoAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinition");
            }


            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ProcessDefinitionEntry>("/process-definitions/{processDefinitionId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a process definition image Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetProcessDefinitionImage(string processDefinitionId, int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<System.IO.Stream> localVarResponse = GetProcessDefinitionImageWithHttpInfo(processDefinitionId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a process definition image Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<System.IO.Stream> GetProcessDefinitionImageWithHttpInfo(string processDefinitionId, int operationIndex = 0)
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinitionImage");
            }

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/png"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinitionImage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<System.IO.Stream>("/process-definitions/{processDefinitionId}/image", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinitionImage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a process definition image Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetProcessDefinitionImageAsync(string processDefinitionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<System.IO.Stream> localVarResponse = await GetProcessDefinitionImageWithHttpInfoAsync(processDefinitionId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a process definition image Gets an image that represents a single process definition identified by **processDefinitionId**.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<System.IO.Stream>> GetProcessDefinitionImageWithHttpInfoAsync(string processDefinitionId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinitionImage");
            }


            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/png"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinitionImage";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<System.IO.Stream>("/process-definitions/{processDefinitionId}/image", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinitionImage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a start form model Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaskFormModelPaging</returns>
        public TaskFormModelPaging GetProcessDefinitionStartFormModel(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<TaskFormModelPaging> localVarResponse = GetProcessDefinitionStartFormModelWithHttpInfo(processDefinitionId, properties);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a start form model Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaskFormModelPaging</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<TaskFormModelPaging> GetProcessDefinitionStartFormModelWithHttpInfo(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0)
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinitionStartFormModel");
            }

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinitionStartFormModel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TaskFormModelPaging>("/process-definitions/{processDefinitionId}/start-form-model", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinitionStartFormModel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a start form model Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaskFormModelPaging</returns>
        public async System.Threading.Tasks.Task<TaskFormModelPaging> GetProcessDefinitionStartFormModelAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<TaskFormModelPaging> localVarResponse = await GetProcessDefinitionStartFormModelWithHttpInfoAsync(processDefinitionId, properties, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a start form model Gets a model of the start form type definition.  An authenticated user will have access to all start form models. In a network, only start form models that are inside the given network are returned. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="processDefinitionId">The identifier of a process definition.</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaskFormModelPaging)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<TaskFormModelPaging>> GetProcessDefinitionStartFormModelWithHttpInfoAsync(string processDefinitionId, List<string> properties = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'processDefinitionId' is set
            if (processDefinitionId == null)
            {
                throw new Variograma.AlfrescoWorkflow.Client.ApiException(400, "Missing required parameter 'processDefinitionId' when calling ProcessDefinitionsApi->GetProcessDefinitionStartFormModel");
            }


            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("processDefinitionId", Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToString(processDefinitionId)); // path parameter
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.GetProcessDefinitionStartFormModel";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TaskFormModelPaging>("/process-definitions/{processDefinitionId}/start-form-model", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProcessDefinitionStartFormModel", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List process definitions Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ProcessDefinitionPaging</returns>
        public ProcessDefinitionPaging ListProcessDefinitions(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionPaging> localVarResponse = ListProcessDefinitionsWithHttpInfo(skipCount, maxItems, properties, orderBy, where);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List process definitions Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ProcessDefinitionPaging</returns>
        public Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionPaging> ListProcessDefinitionsWithHttpInfo(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0)
        {
            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (skipCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "skipCount", skipCount));
            }
            if (maxItems != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "maxItems", maxItems));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "orderBy", orderBy));
            }
            if (where != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "where", where));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.ListProcessDefinitions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ProcessDefinitionPaging>("/process-definitions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListProcessDefinitions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List process definitions Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProcessDefinitionPaging</returns>
        public async System.Threading.Tasks.Task<ProcessDefinitionPaging> ListProcessDefinitionsAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionPaging> localVarResponse = await ListProcessDefinitionsWithHttpInfoAsync(skipCount, maxItems, properties, orderBy, where, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List process definitions Gets a list of process definitions.  In non-network deployments, any authenticated user will see all the process definitions.  If networks are enabled, the network admin can only see the deployments in the given network. 
        /// </summary>
        /// <exception cref="Variograma.AlfrescoWorkflow.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="skipCount">The number of entities that  exist in the collection before those included in this list. (optional)</param>
        /// <param name="maxItems">The maximum number of items to return in the list. (optional)</param>
        /// <param name="properties">A list of property names. You can use the properties parameter to restrict the number of returned properties. (optional)</param>
        /// <param name="orderBy">A string to control the order of the entities returned in a list. You can use the **orderby** parameter to sort the list by one or more fields.  Each field has a default sort order, which is normally ascending order. Read the API method implementation notes above to check if any fields used in this method have a descending default search order.  To sort the entities in a specific order, you can use the **ASC** and **DESC** keywords for any field.  (optional)</param>
        /// <param name="where">A string to restrict the returned objects by using a predicate. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProcessDefinitionPaging)</returns>
        public async System.Threading.Tasks.Task<Variograma.AlfrescoWorkflow.Client.ApiResponse<ProcessDefinitionPaging>> ListProcessDefinitionsWithHttpInfoAsync(int? skipCount = default(int?), int? maxItems = default(int?), List<string> properties = default(List<string>), List<string> orderBy = default(List<string>), string where = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Variograma.AlfrescoWorkflow.Client.RequestOptions localVarRequestOptions = new Variograma.AlfrescoWorkflow.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Variograma.AlfrescoWorkflow.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (skipCount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "skipCount", skipCount));
            }
            if (maxItems != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "maxItems", maxItems));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "properties", properties));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("csv", "orderBy", orderBy));
            }
            if (where != null)
            {
                localVarRequestOptions.QueryParameters.Add(Variograma.AlfrescoWorkflow.Client.ClientUtils.ParameterToMultiMap("", "where", where));
            }

            localVarRequestOptions.Operation = "ProcessDefinitionsApi.ListProcessDefinitions";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Variograma.AlfrescoWorkflow.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ProcessDefinitionPaging>("/process-definitions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListProcessDefinitions", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
