/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing Candidate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CandidateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Candidate
        //private Candidate instance;

        public CandidateTests()
        {
            // TODO uncomment below to create an instance of Candidate
            //instance = new Candidate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Candidate
        /// </summary>
        [Fact]
        public void CandidateInstanceTest()
        {
            // TODO uncomment below to test "IsType" Candidate
            //Assert.IsType<Candidate>(instance);
        }


        /// <summary>
        /// Test the property 'CandidateType'
        /// </summary>
        [Fact]
        public void CandidateTypeTest()
        {
            // TODO unit test for the property 'CandidateType'
        }
        /// <summary>
        /// Test the property 'CandidateId'
        /// </summary>
        [Fact]
        public void CandidateIdTest()
        {
            // TODO unit test for the property 'CandidateId'
        }

    }

}
