/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentEntry
        //private DeploymentEntry instance;

        public DeploymentEntryTests()
        {
            // TODO uncomment below to create an instance of DeploymentEntry
            //instance = new DeploymentEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentEntry
        /// </summary>
        [Fact]
        public void DeploymentEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentEntry
            //Assert.IsType<DeploymentEntry>(instance);
        }


        /// <summary>
        /// Test the property 'Entry'
        /// </summary>
        [Fact]
        public void EntryTest()
        {
            // TODO unit test for the property 'Entry'
        }

    }

}
