/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing DeploymentPaging
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeploymentPagingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeploymentPaging
        //private DeploymentPaging instance;

        public DeploymentPagingTests()
        {
            // TODO uncomment below to create an instance of DeploymentPaging
            //instance = new DeploymentPaging();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentPaging
        /// </summary>
        [Fact]
        public void DeploymentPagingInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeploymentPaging
            //Assert.IsType<DeploymentPaging>(instance);
        }


        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Fact]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }

    }

}
