/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorError
        //private ErrorError instance;

        public ErrorErrorTests()
        {
            // TODO uncomment below to create an instance of ErrorError
            //instance = new ErrorError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorError
        /// </summary>
        [Fact]
        public void ErrorErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorError
            //Assert.IsType<ErrorError>(instance);
        }


        /// <summary>
        /// Test the property 'ErrorKey'
        /// </summary>
        [Fact]
        public void ErrorKeyTest()
        {
            // TODO unit test for the property 'ErrorKey'
        }
        /// <summary>
        /// Test the property 'StatusCode'
        /// </summary>
        [Fact]
        public void StatusCodeTest()
        {
            // TODO unit test for the property 'StatusCode'
        }
        /// <summary>
        /// Test the property 'BriefSummary'
        /// </summary>
        [Fact]
        public void BriefSummaryTest()
        {
            // TODO unit test for the property 'BriefSummary'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Fact]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'DescriptionURL'
        /// </summary>
        [Fact]
        public void DescriptionURLTest()
        {
            // TODO unit test for the property 'DescriptionURL'
        }
        /// <summary>
        /// Test the property 'LogId'
        /// </summary>
        [Fact]
        public void LogIdTest()
        {
            // TODO unit test for the property 'LogId'
        }

    }

}
