/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ItemPagingList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemPagingListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemPagingList
        //private ItemPagingList instance;

        public ItemPagingListTests()
        {
            // TODO uncomment below to create an instance of ItemPagingList
            //instance = new ItemPagingList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemPagingList
        /// </summary>
        [Fact]
        public void ItemPagingListInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemPagingList
            //Assert.IsType<ItemPagingList>(instance);
        }


        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
        /// <summary>
        /// Test the property 'Entries'
        /// </summary>
        [Fact]
        public void EntriesTest()
        {
            // TODO unit test for the property 'Entries'
        }

    }

}
