/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ItemBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemBody
        //private ItemBody instance;

        public ItemBodyTests()
        {
            // TODO uncomment below to create an instance of ItemBody
            //instance = new ItemBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemBody
        /// </summary>
        [Fact]
        public void ItemBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemBody
            //Assert.IsType<ItemBody>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
