/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing Pagination
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Pagination
        //private Pagination instance;

        public PaginationTests()
        {
            // TODO uncomment below to create an instance of Pagination
            //instance = new Pagination();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Pagination
        /// </summary>
        [Fact]
        public void PaginationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Pagination
            //Assert.IsType<Pagination>(instance);
        }


        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'HasMoreItems'
        /// </summary>
        [Fact]
        public void HasMoreItemsTest()
        {
            // TODO unit test for the property 'HasMoreItems'
        }
        /// <summary>
        /// Test the property 'TotalItems'
        /// </summary>
        [Fact]
        public void TotalItemsTest()
        {
            // TODO unit test for the property 'TotalItems'
        }
        /// <summary>
        /// Test the property 'SkipCount'
        /// </summary>
        [Fact]
        public void SkipCountTest()
        {
            // TODO unit test for the property 'SkipCount'
        }
        /// <summary>
        /// Test the property 'MaxItems'
        /// </summary>
        [Fact]
        public void MaxItemsTest()
        {
            // TODO unit test for the property 'MaxItems'
        }

    }

}
