/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing Person
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Person
        //private Person instance;

        public PersonTests()
        {
            // TODO uncomment below to create an instance of Person
            //instance = new Person();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Person
        /// </summary>
        [Fact]
        public void PersonInstanceTest()
        {
            // TODO uncomment below to test "IsType" Person
            //Assert.IsType<Person>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AvatarId'
        /// </summary>
        [Fact]
        public void AvatarIdTest()
        {
            // TODO unit test for the property 'AvatarId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'SkypeId'
        /// </summary>
        [Fact]
        public void SkypeIdTest()
        {
            // TODO unit test for the property 'SkypeId'
        }
        /// <summary>
        /// Test the property 'GoogleId'
        /// </summary>
        [Fact]
        public void GoogleIdTest()
        {
            // TODO unit test for the property 'GoogleId'
        }
        /// <summary>
        /// Test the property 'InstantMessageId'
        /// </summary>
        [Fact]
        public void InstantMessageIdTest()
        {
            // TODO unit test for the property 'InstantMessageId'
        }
        /// <summary>
        /// Test the property 'JobTitle'
        /// </summary>
        [Fact]
        public void JobTitleTest()
        {
            // TODO unit test for the property 'JobTitle'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Fact]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Telephone'
        /// </summary>
        [Fact]
        public void TelephoneTest()
        {
            // TODO unit test for the property 'Telephone'
        }
        /// <summary>
        /// Test the property 'StatusUpdatedAt'
        /// </summary>
        [Fact]
        public void StatusUpdatedAtTest()
        {
            // TODO unit test for the property 'StatusUpdatedAt'
        }
        /// <summary>
        /// Test the property 'UserStatus'
        /// </summary>
        [Fact]
        public void UserStatusTest()
        {
            // TODO unit test for the property 'UserStatus'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'EmailNotificationsEnabled'
        /// </summary>
        [Fact]
        public void EmailNotificationsEnabledTest()
        {
            // TODO unit test for the property 'EmailNotificationsEnabled'
        }

    }

}
