/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessBody
        //private ProcessBody instance;

        public ProcessBodyTests()
        {
            // TODO uncomment below to create an instance of ProcessBody
            //instance = new ProcessBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessBody
        /// </summary>
        [Fact]
        public void ProcessBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessBody
            //Assert.IsType<ProcessBody>(instance);
        }


        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Fact]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
