/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing Process
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Process
        //private Process instance;

        public ProcessTests()
        {
            // TODO uncomment below to create an instance of Process
            //instance = new Process();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Process
        /// </summary>
        [Fact]
        public void ProcessInstanceTest()
        {
            // TODO uncomment below to test "IsType" Process
            //Assert.IsType<Process>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Fact]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'EndedAt'
        /// </summary>
        [Fact]
        public void EndedAtTest()
        {
            // TODO unit test for the property 'EndedAt'
        }
        /// <summary>
        /// Test the property 'DurationInMs'
        /// </summary>
        [Fact]
        public void DurationInMsTest()
        {
            // TODO unit test for the property 'DurationInMs'
        }
        /// <summary>
        /// Test the property 'StartActivityDefinitionId'
        /// </summary>
        [Fact]
        public void StartActivityDefinitionIdTest()
        {
            // TODO unit test for the property 'StartActivityDefinitionId'
        }
        /// <summary>
        /// Test the property 'EndActivityDefinitionId'
        /// </summary>
        [Fact]
        public void EndActivityDefinitionIdTest()
        {
            // TODO unit test for the property 'EndActivityDefinitionId'
        }
        /// <summary>
        /// Test the property 'StartUserId'
        /// </summary>
        [Fact]
        public void StartUserIdTest()
        {
            // TODO unit test for the property 'StartUserId'
        }
        /// <summary>
        /// Test the property 'DeleteReason'
        /// </summary>
        [Fact]
        public void DeleteReasonTest()
        {
            // TODO unit test for the property 'DeleteReason'
        }

    }

}
