/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinition
        //private ProcessDefinition instance;

        public ProcessDefinitionTests()
        {
            // TODO uncomment below to create an instance of ProcessDefinition
            //instance = new ProcessDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessDefinition
        /// </summary>
        [Fact]
        public void ProcessDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessDefinition
            //Assert.IsType<ProcessDefinition>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Fact]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'StartFormResourceKey'
        /// </summary>
        [Fact]
        public void StartFormResourceKeyTest()
        {
            // TODO unit test for the property 'StartFormResourceKey'
        }
        /// <summary>
        /// Test the property 'GraphicNotationDefined'
        /// </summary>
        [Fact]
        public void GraphicNotationDefinedTest()
        {
            // TODO unit test for the property 'GraphicNotationDefined'
        }

    }

}
