/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing ProcessBodyVariable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProcessBodyVariableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProcessBodyVariable
        //private ProcessBodyVariable instance;

        public ProcessBodyVariableTests()
        {
            // TODO uncomment below to create an instance of ProcessBodyVariable
            //instance = new ProcessBodyVariable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessBodyVariable
        /// </summary>
        [Fact]
        public void ProcessBodyVariableInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProcessBodyVariable
            //Assert.IsType<ProcessBodyVariable>(instance);
        }


        /// <summary>
        /// Test the property 'BpmAssignee'
        /// </summary>
        [Fact]
        public void BpmAssigneeTest()
        {
            // TODO unit test for the property 'BpmAssignee'
        }
        /// <summary>
        /// Test the property 'BpmSendEMailNotifications'
        /// </summary>
        [Fact]
        public void BpmSendEMailNotificationsTest()
        {
            // TODO unit test for the property 'BpmSendEMailNotifications'
        }
        /// <summary>
        /// Test the property 'BpmWorkflowPriority'
        /// </summary>
        [Fact]
        public void BpmWorkflowPriorityTest()
        {
            // TODO unit test for the property 'BpmWorkflowPriority'
        }

    }

}
