/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing Task
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Task
        //private Task instance;

        public TaskTests()
        {
            // TODO uncomment below to create an instance of Task
            //instance = new Task();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Task
        /// </summary>
        [Fact]
        public void TaskInstanceTest()
        {
            // TODO uncomment below to test "IsType" Task
            //Assert.IsType<Task>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ProcessId'
        /// </summary>
        [Fact]
        public void ProcessIdTest()
        {
            // TODO unit test for the property 'ProcessId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Fact]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ActivityDefinitionId'
        /// </summary>
        [Fact]
        public void ActivityDefinitionIdTest()
        {
            // TODO unit test for the property 'ActivityDefinitionId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DueAt'
        /// </summary>
        [Fact]
        public void DueAtTest()
        {
            // TODO unit test for the property 'DueAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'EndedAt'
        /// </summary>
        [Fact]
        public void EndedAtTest()
        {
            // TODO unit test for the property 'EndedAt'
        }
        /// <summary>
        /// Test the property 'DurationInMs'
        /// </summary>
        [Fact]
        public void DurationInMsTest()
        {
            // TODO unit test for the property 'DurationInMs'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Assignee'
        /// </summary>
        [Fact]
        public void AssigneeTest()
        {
            // TODO unit test for the property 'Assignee'
        }
        /// <summary>
        /// Test the property 'FormResourceKey'
        /// </summary>
        [Fact]
        public void FormResourceKeyTest()
        {
            // TODO unit test for the property 'FormResourceKey'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
