/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Variograma.AlfrescoWorkflow.Model;
using Variograma.AlfrescoWorkflow.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Variograma.AlfrescoWorkflow.Test.Model
{
    /// <summary>
    ///  Class for testing VariableEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VariableEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VariableEntry
        //private VariableEntry instance;

        public VariableEntryTests()
        {
            // TODO uncomment below to create an instance of VariableEntry
            //instance = new VariableEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VariableEntry
        /// </summary>
        [Fact]
        public void VariableEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" VariableEntry
            //Assert.IsType<VariableEntry>(instance);
        }


        /// <summary>
        /// Test the property 'Entry'
        /// </summary>
        [Fact]
        public void EntryTest()
        {
            // TODO unit test for the property 'Entry'
        }

    }

}
