/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Api;
// uncomment below to import models
//using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Test.Api
{
    /// <summary>
    ///  Class for testing DeploymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DeploymentsApiTests : IDisposable
    {
        private DeploymentsApi instance;

        public DeploymentsApiTests()
        {
            instance = new DeploymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeploymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DeploymentsApi
            //Assert.IsType<DeploymentsApi>(instance);
        }

        /// <summary>
        /// Test DeleteDeployment
        /// </summary>
        [Fact]
        public void DeleteDeploymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deploymentId = null;
            //instance.DeleteDeployment(deploymentId);
        }

        /// <summary>
        /// Test GetDeployment
        /// </summary>
        [Fact]
        public void GetDeploymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deploymentId = null;
            //List<string> properties = null;
            //var response = instance.GetDeployment(deploymentId, properties);
            //Assert.IsType<DeploymentEntry>(response);
        }

        /// <summary>
        /// Test ListDeployments
        /// </summary>
        [Fact]
        public void ListDeploymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.ListDeployments(skipCount, maxItems, properties);
            //Assert.IsType<DeploymentPaging>(response);
        }
    }
}
