/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Api;
// uncomment below to import models
//using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Test.Api
{
    /// <summary>
    ///  Class for testing ProcessDefinitionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProcessDefinitionsApiTests : IDisposable
    {
        private ProcessDefinitionsApi instance;

        public ProcessDefinitionsApiTests()
        {
            instance = new ProcessDefinitionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessDefinitionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProcessDefinitionsApi
            //Assert.IsType<ProcessDefinitionsApi>(instance);
        }

        /// <summary>
        /// Test GetProcessDefinition
        /// </summary>
        [Fact]
        public void GetProcessDefinitionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processDefinitionId = null;
            //List<string> properties = null;
            //var response = instance.GetProcessDefinition(processDefinitionId, properties);
            //Assert.IsType<ProcessDefinitionEntry>(response);
        }

        /// <summary>
        /// Test GetProcessDefinitionImage
        /// </summary>
        [Fact]
        public void GetProcessDefinitionImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processDefinitionId = null;
            //var response = instance.GetProcessDefinitionImage(processDefinitionId);
            //Assert.IsType<System.IO.Stream>(response);
        }

        /// <summary>
        /// Test GetProcessDefinitionStartFormModel
        /// </summary>
        [Fact]
        public void GetProcessDefinitionStartFormModelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processDefinitionId = null;
            //List<string> properties = null;
            //var response = instance.GetProcessDefinitionStartFormModel(processDefinitionId, properties);
            //Assert.IsType<TaskFormModelPaging>(response);
        }

        /// <summary>
        /// Test ListProcessDefinitions
        /// </summary>
        [Fact]
        public void ListProcessDefinitionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //List<string> orderBy = null;
            //string where = null;
            //var response = instance.ListProcessDefinitions(skipCount, maxItems, properties, orderBy, where);
            //Assert.IsType<ProcessDefinitionPaging>(response);
        }
    }
}
