/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Api;
// uncomment below to import models
//using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Test.Api
{
    /// <summary>
    ///  Class for testing ProcessesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProcessesApiTests : IDisposable
    {
        private ProcessesApi instance;

        public ProcessesApiTests()
        {
            instance = new ProcessesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProcessesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProcessesApi
            //Assert.IsType<ProcessesApi>(instance);
        }

        /// <summary>
        /// Test CreateProcess
        /// </summary>
        [Fact]
        public void CreateProcessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessBody processBody = null;
            //var response = instance.CreateProcess(processBody);
            //Assert.IsType<ProcessEntry>(response);
        }

        /// <summary>
        /// Test CreateProcessItem
        /// </summary>
        [Fact]
        public void CreateProcessItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //ItemBody itemBody = null;
            //var response = instance.CreateProcessItem(processId, itemBody);
            //Assert.IsType<ItemPaging>(response);
        }

        /// <summary>
        /// Test CreateProcessVariable
        /// </summary>
        [Fact]
        public void CreateProcessVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //string variableName = null;
            //VariableBody variableBody = null;
            //var response = instance.CreateProcessVariable(processId, variableName, variableBody);
            //Assert.IsType<VariableEntry>(response);
        }

        /// <summary>
        /// Test CreateProcessVariables
        /// </summary>
        [Fact]
        public void CreateProcessVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //VariableBody variableBody = null;
            //var response = instance.CreateProcessVariables(processId, variableBody);
            //Assert.IsType<VariableEntry>(response);
        }

        /// <summary>
        /// Test DeleteProcess
        /// </summary>
        [Fact]
        public void DeleteProcessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //instance.DeleteProcess(processId);
        }

        /// <summary>
        /// Test DeleteProcessItem
        /// </summary>
        [Fact]
        public void DeleteProcessItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //string itemId = null;
            //instance.DeleteProcessItem(processId, itemId);
        }

        /// <summary>
        /// Test DeleteProcessVariable
        /// </summary>
        [Fact]
        public void DeleteProcessVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //string variableName = null;
            //instance.DeleteProcessVariable(processId, variableName);
        }

        /// <summary>
        /// Test GetProcess
        /// </summary>
        [Fact]
        public void GetProcessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //List<string> properties = null;
            //var response = instance.GetProcess(processId, properties);
            //Assert.IsType<ProcessEntry>(response);
        }

        /// <summary>
        /// Test ListProcessItems
        /// </summary>
        [Fact]
        public void ListProcessItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.ListProcessItems(processId, skipCount, maxItems, properties);
            //Assert.IsType<ItemPaging>(response);
        }

        /// <summary>
        /// Test ListProcessVariables
        /// </summary>
        [Fact]
        public void ListProcessVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.ListProcessVariables(processId, skipCount, maxItems, properties);
            //Assert.IsType<VariablePaging>(response);
        }

        /// <summary>
        /// Test ListProcesses
        /// </summary>
        [Fact]
        public void ListProcessesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //List<string> orderBy = null;
            //string where = null;
            //var response = instance.ListProcesses(skipCount, maxItems, properties, orderBy, where);
            //Assert.IsType<ProcessPaging>(response);
        }
    }
}
