/*
 * Alfresco Content Services REST API
 *
 * **Workflow API**  Provides access to the workflow features of Alfresco Content Services. 
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Variograma.AlfrescoWorkflow.Client;
using Variograma.AlfrescoWorkflow.Api;
// uncomment below to import models
//using Variograma.AlfrescoWorkflow.Model;

namespace Variograma.AlfrescoWorkflow.Test.Api
{
    /// <summary>
    ///  Class for testing TasksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TasksApiTests : IDisposable
    {
        private TasksApi instance;

        public TasksApiTests()
        {
            instance = new TasksApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TasksApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TasksApi
            //Assert.IsType<TasksApi>(instance);
        }

        /// <summary>
        /// Test CreateTaskItem
        /// </summary>
        [Fact]
        public void CreateTaskItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //ItemBody itemBody = null;
            //var response = instance.CreateTaskItem(taskId, itemBody);
            //Assert.IsType<ItemPaging>(response);
        }

        /// <summary>
        /// Test CreateTaskVariables
        /// </summary>
        [Fact]
        public void CreateTaskVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //Variable variable = null;
            //var response = instance.CreateTaskVariables(taskId, variable);
            //Assert.IsType<VariableEntry>(response);
        }

        /// <summary>
        /// Test DeleteTaskItem
        /// </summary>
        [Fact]
        public void DeleteTaskItemTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //string itemId = null;
            //instance.DeleteTaskItem(taskId, itemId);
        }

        /// <summary>
        /// Test DeleteTaskVariable
        /// </summary>
        [Fact]
        public void DeleteTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //string variableName = null;
            //instance.DeleteTaskVariable(taskId, variableName);
        }

        /// <summary>
        /// Test GetTask
        /// </summary>
        [Fact]
        public void GetTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //List<string> properties = null;
            //var response = instance.GetTask(taskId, properties);
            //Assert.IsType<TaskEntry>(response);
        }

        /// <summary>
        /// Test GetTaskFormModel
        /// </summary>
        [Fact]
        public void GetTaskFormModelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.GetTaskFormModel(taskId, skipCount, maxItems, properties);
            //Assert.IsType<TaskFormModelPaging>(response);
        }

        /// <summary>
        /// Test ListTaskCandidates
        /// </summary>
        [Fact]
        public void ListTaskCandidatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.ListTaskCandidates(taskId, skipCount, maxItems, properties);
            //Assert.IsType<CandidatePaging>(response);
        }

        /// <summary>
        /// Test ListTaskItems
        /// </summary>
        [Fact]
        public void ListTaskItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //var response = instance.ListTaskItems(taskId, skipCount, maxItems, properties);
            //Assert.IsType<ItemPaging>(response);
        }

        /// <summary>
        /// Test ListTaskVariables
        /// </summary>
        [Fact]
        public void ListTaskVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //string where = null;
            //var response = instance.ListTaskVariables(taskId, skipCount, maxItems, properties, where);
            //Assert.IsType<VariablePaging>(response);
        }

        /// <summary>
        /// Test ListTasks
        /// </summary>
        [Fact]
        public void ListTasksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //List<string> orderBy = null;
            //string where = null;
            //var response = instance.ListTasks(skipCount, maxItems, properties, orderBy, where);
            //Assert.IsType<TaskPaging>(response);
        }

        /// <summary>
        /// Test ListTasksForProcess
        /// </summary>
        [Fact]
        public void ListTasksForProcessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processId = null;
            //int? skipCount = null;
            //int? maxItems = null;
            //List<string> properties = null;
            //List<string> orderBy = null;
            //var response = instance.ListTasksForProcess(processId, skipCount, maxItems, properties, orderBy);
            //Assert.IsType<TaskPaging>(response);
        }

        /// <summary>
        /// Test UpdateTask
        /// </summary>
        [Fact]
        public void UpdateTaskTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //TaskBody taskBody = null;
            //int? select = null;
            //var response = instance.UpdateTask(taskId, taskBody, select);
            //Assert.IsType<TaskEntry>(response);
        }

        /// <summary>
        /// Test UpdateTaskVariable
        /// </summary>
        [Fact]
        public void UpdateTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string taskId = null;
            //string variableName = null;
            //Variable variableBody = null;
            //var response = instance.UpdateTaskVariable(taskId, variableName, variableBody);
            //Assert.IsType<VariableEntry>(response);
        }
    }
}
